### ISSUE TITLE
cannot create new branch in iOS GitHub

### ISSUE THREAD

**Issue by ricksentam** [aws/dotnet#26]

**Comment by ashishdhingra** [comment]
Hi @ricksentam,

Good morning.

I'm not sure if you created this issue in the correct repository. Please share the repository URL, I could try to transfer this issue to that repository.

Thanks,
Ashish

**Comment by ricksentam** [comment]
I am sorry, maybe just my mistake. When I trying to use GitHub iOS version, I tried to create new branch (in case I mess up the master branch) , but I couldn't find a way to do that.

**Comment by ricksentam** [comment]
I am sorry, maybe just my mistake. When I trying to use GitHub iOS version, I tried to create new branch (in case I mess up the master branch) , but I couldn't find a way to do that.

**Comment by ricksentam** [comment]
I am sorry, maybe just my mistake. When I trying to use GitHub iOS version, I tried to create new branch (in case I mess up the master branch) , but I couldn't find a way to do that.

**Comment by ricksentam** [comment]
I am sorry, maybe just my mistake. When I trying to use GitHub iOS version, I tried to create new branch (in case I mess up the master branch) , but I couldn't find a way to do that.

**Comment by ricksentam** [comment]
I am sorry, maybe just my mistake. When I trying to use GitHub iOS version, I tried to create new branch (in case I mess up the master branch) , but I couldn't find a way to do that.

**Comment by ricksentam** [comment]
I am sorry, maybe just my mistake. When I trying to use GitHub iOS version, I tried to create new branch (in case I mess up the master branch) , but I couldn't find a way to do that.

**Comment by ashishdhingra** [comment]
Wrong repository. Please contact GitHub support.

**Comment by ricksentam** [comment]
#3 #6

**Comment by ricksentam** [comment]
`add close label for it`
