### ISSUE TITLE
Aws S3 ListBucketContentsAsync() works on windows and ios not on android (Unity)

### ISSUE THREAD

**Issue by JakobJJ** [aws/dotnet#43]
I have created a application in Unity and it uses the AWSSDK specifically S3.
Using this function works well in the Editor and on ios but it does not work on android. Is it just me that has this issue with android and the aws sdk in Unity?

**The error that occurs on android is this.**
Info IL2CPP AmazonS3Client 17|2023-04-17T11:27:52.299Z|ERROR|An exception of type HttpRequestException was handled in ErrorHandler. --> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error getting response stream (ReadDoneAsync2): ReceiveFailure

**The function being run is this**
```C#
public async Task<bool> ListBucketContentsAsync()
    {
        try
        {
            var request = new ListObjectsV2Request
            {
                BucketName = S3BucketName,
                MaxKeys = 100,
            };

            Debug.Log("--------------------------------------");
            Debug.Log($"Listing the contents of {S3BucketName}:");
            Debug.Log("--------------------------------------");

            ListObjectsV2Response response;

            do
            {
                response = await Client.ListObjectsV2Async(request);

                response.S3Objects
                    .ForEach(obj => Debug.Log($"{obj.Key,-35}{obj.LastModified.ToShortDateString(),10}{obj.Size,10}"));

                // If the response is truncated, set the request ContinuationToken
                // from the NextContinuationToken property of the response.
                request.ContinuationToken = response.NextContinuationToken;
            }
            while (response.IsTruncated);

            return true;
        }
        catch (AmazonS3Exception ex)
        {
            Debug.Log($"Error encountered on server. Message:'{ex.Message}' getting list of objects.");
            return false;
        }
    }
```

**Comment by ashishdhingra** [comment]
@JakobJJ Good afternoon. Please advise if you have followed [Special considerations for Unity support](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/unity-special.html).
