### ISSUE TITLE
Fetching ECR authorization token to use to login with the docker CLI

### ISSUE THREAD

**Issue by JLOrdaz** [aws/dotnet#54]
I try to publish container to ECR and get error with this message:

Fetching ECR authorization token to use to login with the docker CLI

aws-cli/2.17.42 Python/3.11.9 Windows/10 exe/AMD64

Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:17:17 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.34.0 (165256)
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:15 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

I have project web i need update to ECR to use Fargate.

**Comment by bhoradc** [comment]
Hello @JLOrdaz, 

Thank you for reaching out regarding the issue you're experiencing with pushing a Docker container image to ECR. 

I believe this isn't the correct repo for reporting this problem (unless you are using any .NET SDK component). I would recommend opening an issue in the https://github.com/aws/aws-cli/issues repository instead. I will hence close this out. 

Regards, 
Chaitanya

**Comment by JLOrdaz** [comment]
OK, thanks
